set_property SRC_FILE_INFO {cfile:C:/Vivado_projects/LONGSOON-huangchao/poreject/CPU_1/CPU_1.srcs/constrs_1/new/CPU_1.xdc rfile:../../../CPU_1.srcs/constrs_1/new/CPU_1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {io_exit}]
