set_property -dict {PACKAGE_PIN AC19 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVCMOS33} [get_ports resetn]

#LED
set_property -dict {PACKAGE_PIN H7 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN F7 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN G8 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33} [get_ports {led[7]}]

set_property -dict {PACKAGE_PIN J8  IOSTANDARD LVCMOS33} [get_ports {led[8]}]
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33} [get_ports {led[9]}]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS33} [get_ports {led[10]}]
set_property -dict {PACKAGE_PIN G9  IOSTANDARD LVCMOS33} [get_ports {led[11]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {led[12]}]
set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33} [get_ports {led[13]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {led[14]}]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33} [get_ports {led[15]}]

#seg
set_property PACKAGE_PIN D3  [get_ports {num_scan_select[7]}]
set_property PACKAGE_PIN D25 [get_ports {num_scan_select[6]}]
set_property PACKAGE_PIN D26 [get_ports {num_scan_select[5]}]
set_property PACKAGE_PIN E25 [get_ports {num_scan_select[4]}]
set_property PACKAGE_PIN E26 [get_ports {num_scan_select[3]}]
set_property PACKAGE_PIN G25 [get_ports {num_scan_select[2]}]
set_property PACKAGE_PIN G26 [get_ports {num_scan_select[1]}]
set_property PACKAGE_PIN H26 [get_ports {num_scan_select[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_scan_select[7]}]

set_property PACKAGE_PIN C4 [get_ports {num_seg[7]}]
set_property PACKAGE_PIN A2 [get_ports {num_seg[6]}]
set_property PACKAGE_PIN D4 [get_ports {num_seg[5]}]
set_property PACKAGE_PIN E5 [get_ports {num_seg[4]}]
set_property PACKAGE_PIN B4 [get_ports {num_seg[3]}]
set_property PACKAGE_PIN B2 [get_ports {num_seg[2]}]
set_property PACKAGE_PIN E6 [get_ports {num_seg[1]}]
set_property PACKAGE_PIN C3 [get_ports {num_seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_seg[0]}]



# Switch 约束
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports {sw[0]}]
set_property -dict {PACKAGE_PIN AA7 IOSTANDARD LVCMOS33} [get_ports {sw[1]}]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports {sw[2]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports {sw[3]}]
set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVCMOS33} [get_ports {sw[4]}]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports {sw[5]}]
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS33} [get_ports {sw[6]}]
set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS33} [get_ports {sw[7]}]
